// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type Page struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Name      string    `json:"name"`
	BgColor   *string   `json:"bg_color"`
	BgImage   *string   `json:"bg_image"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Config    string    `json:"config"`
}

type RssFeed struct {
	Url         string     `json:"url"`
	Title       string     `json:"title"`
	Content     string     `json:"content"`
	LastFetched *time.Time `json:"last_fetched"`
	LastError   *string    `json:"last_error"`
	CreatedAt   time.Time  `json:"created_at"`
}

type VisitedLink struct {
	ID        int64     `json:"id"`
	UserID    string    `json:"user_id"`
	LinkUrl   string    `json:"link_url"`
	VisitedAt time.Time `json:"visited_at"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}

type Widget struct {
	ID          string    `json:"id"`
	PageID      string    `json:"page_id"`
	Title       string    `json:"title"`
	WidgetType  string    `json:"widget_type"`
	PosX        int64     `json:"pos_x"`
	PosY        int64     `json:"pos_y"`
	Width       int64     `json:"width"`
	Height      int64     `json:"height"`
	BgColor     *string   `json:"bg_color"`
	TextColor   *string   `json:"text_color"`
	HeaderColor *string   `json:"header_color"`
	Config      string    `json:"config"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
