// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: visited.sql

package dbgen

import (
	"context"
	"time"
)

const cleanupOldVisitedLinks = `-- name: CleanupOldVisitedLinks :exec
DELETE FROM visited_links WHERE visited_at < ?
`

func (q *Queries) CleanupOldVisitedLinks(ctx context.Context, visitedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, cleanupOldVisitedLinks, visitedAt)
	return err
}

const getVisitedLinks = `-- name: GetVisitedLinks :many
SELECT DISTINCT link_url FROM visited_links WHERE user_id = ? AND visited_at > ?
`

type GetVisitedLinksParams struct {
	UserID    string    `json:"user_id"`
	VisitedAt time.Time `json:"visited_at"`
}

func (q *Queries) GetVisitedLinks(ctx context.Context, arg GetVisitedLinksParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getVisitedLinks, arg.UserID, arg.VisitedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var link_url string
		if err := rows.Scan(&link_url); err != nil {
			return nil, err
		}
		items = append(items, link_url)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLinkVisited = `-- name: MarkLinkVisited :exec
INSERT INTO visited_links (user_id, link_url, visited_at) VALUES (?, ?, ?)
`

type MarkLinkVisitedParams struct {
	UserID    string    `json:"user_id"`
	LinkUrl   string    `json:"link_url"`
	VisitedAt time.Time `json:"visited_at"`
}

func (q *Queries) MarkLinkVisited(ctx context.Context, arg MarkLinkVisitedParams) error {
	_, err := q.db.ExecContext(ctx, markLinkVisited, arg.UserID, arg.LinkUrl, arg.VisitedAt)
	return err
}
