// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: widgets.sql

package dbgen

import (
	"context"
	"time"
)

const createWidget = `-- name: CreateWidget :exec
INSERT INTO widgets (id, page_id, title, widget_type, pos_x, pos_y, width, height, bg_color, text_color, header_color, config, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateWidgetParams struct {
	ID          string    `json:"id"`
	PageID      string    `json:"page_id"`
	Title       string    `json:"title"`
	WidgetType  string    `json:"widget_type"`
	PosX        int64     `json:"pos_x"`
	PosY        int64     `json:"pos_y"`
	Width       int64     `json:"width"`
	Height      int64     `json:"height"`
	BgColor     *string   `json:"bg_color"`
	TextColor   *string   `json:"text_color"`
	HeaderColor *string   `json:"header_color"`
	Config      string    `json:"config"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CreateWidget(ctx context.Context, arg CreateWidgetParams) error {
	_, err := q.db.ExecContext(ctx, createWidget,
		arg.ID,
		arg.PageID,
		arg.Title,
		arg.WidgetType,
		arg.PosX,
		arg.PosY,
		arg.Width,
		arg.Height,
		arg.BgColor,
		arg.TextColor,
		arg.HeaderColor,
		arg.Config,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteWidget = `-- name: DeleteWidget :exec
DELETE FROM widgets WHERE id = ?
`

func (q *Queries) DeleteWidget(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWidget, id)
	return err
}

const getWidgetByID = `-- name: GetWidgetByID :one
SELECT id, page_id, title, widget_type, pos_x, pos_y, width, height, bg_color, text_color, header_color, config, created_at, updated_at FROM widgets WHERE id = ?
`

func (q *Queries) GetWidgetByID(ctx context.Context, id string) (Widget, error) {
	row := q.db.QueryRowContext(ctx, getWidgetByID, id)
	var i Widget
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Title,
		&i.WidgetType,
		&i.PosX,
		&i.PosY,
		&i.Width,
		&i.Height,
		&i.BgColor,
		&i.TextColor,
		&i.HeaderColor,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWidgetsByPageID = `-- name: GetWidgetsByPageID :many
SELECT id, page_id, title, widget_type, pos_x, pos_y, width, height, bg_color, text_color, header_color, config, created_at, updated_at FROM widgets WHERE page_id = ? ORDER BY created_at
`

func (q *Queries) GetWidgetsByPageID(ctx context.Context, pageID string) ([]Widget, error) {
	rows, err := q.db.QueryContext(ctx, getWidgetsByPageID, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Widget{}
	for rows.Next() {
		var i Widget
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.Title,
			&i.WidgetType,
			&i.PosX,
			&i.PosY,
			&i.Width,
			&i.Height,
			&i.BgColor,
			&i.TextColor,
			&i.HeaderColor,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWidget = `-- name: UpdateWidget :exec
UPDATE widgets SET title = ?, widget_type = ?, pos_x = ?, pos_y = ?, width = ?, height = ?, bg_color = ?, text_color = ?, header_color = ?, config = ?, updated_at = ? WHERE id = ?
`

type UpdateWidgetParams struct {
	Title       string    `json:"title"`
	WidgetType  string    `json:"widget_type"`
	PosX        int64     `json:"pos_x"`
	PosY        int64     `json:"pos_y"`
	Width       int64     `json:"width"`
	Height      int64     `json:"height"`
	BgColor     *string   `json:"bg_color"`
	TextColor   *string   `json:"text_color"`
	HeaderColor *string   `json:"header_color"`
	Config      string    `json:"config"`
	UpdatedAt   time.Time `json:"updated_at"`
	ID          string    `json:"id"`
}

func (q *Queries) UpdateWidget(ctx context.Context, arg UpdateWidgetParams) error {
	_, err := q.db.ExecContext(ctx, updateWidget,
		arg.Title,
		arg.WidgetType,
		arg.PosX,
		arg.PosY,
		arg.Width,
		arg.Height,
		arg.BgColor,
		arg.TextColor,
		arg.HeaderColor,
		arg.Config,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
